                                                        Summary per host
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Host IP      ┃ # of success ┃ # of failure ┃ # of errors ┃ List of failed ortest case                                         ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 192.168.0.10 │ 2            │ 2            │ 1           │ ['verify_eos_version', 'verify_reload_cause', 'verify_agent_logs'] │
│ 192.168.0.11 │ 3            │ 1            │ 1           │ ['verify_eos_version', 'verify_reload_cause']                      │
│ 192.168.0.12 │ 2            │ 2            │ 1           │ ['verify_eos_version', 'verify_reload_cause', 'verify_agent_logs'] │
│ 192.168.0.13 │ 3            │ 1            │ 1           │ ['verify_eos_version', 'verify_reload_cause']                      │
│ 192.168.0.14 │ 3            │ 1            │ 1           │ ['verify_eos_version', 'verify_reload_cause']                      │
│ 192.168.0.15 │ 3            │ 1            │ 1           │ ['verify_eos_version', 'verify_reload_cause']                      │
└──────────────┴──────────────┴──────────────┴─────────────┴────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                        Summary per test case
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Test Case           ┃ # of success ┃ # of failure ┃ # of errors ┃ List of failed or error nodes                                                                    ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ verify_eos_version  │ 0            │ 6            │ 0           │ ['192.168.0.10', '192.168.0.11', '192.168.0.12', '192.168.0.13', '192.168.0.14', '192.168.0.15'] │
│ verify_uptime       │ 6            │ 0            │ 0           │ []                                                                                               │
│ verify_reload_cause │ 0            │ 0            │ 6           │ ['192.168.0.10', '192.168.0.11', '192.168.0.12', '192.168.0.13', '192.168.0.14', '192.168.0.15'] │
│ verify_coredump     │ 6            │ 0            │ 0           │ []                                                                                               │
│ verify_agent_logs   │ 4            │ 2            │ 0           │ ['192.168.0.10', '192.168.0.12']                                                                 │
└─────────────────────┴──────────────┴──────────────┴─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                         All tests results
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Device IP    ┃ Test Name           ┃ Test Status ┃ Message(s)                                                                                                                                                                                                   ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 192.168.0.10 │ verify_eos_version  │ failure     │ device is running version 4.27.3F-26379303.4273F (engineering build) not in expected version                                                                                                                 │
│ 192.168.0.10 │ verify_uptime       │ success     │                                                                                                                                                                                                              │
│ 192.168.0.10 │ verify_reload_cause │ error       │ 'response'                                                                                                                                                                                                   │
│ 192.168.0.10 │ verify_coredump     │ success     │                                                                                                                                                                                                              │
│ 192.168.0.10 │ verify_agent_logs   │ failure     │ device reported some agent crashes: ===> /var/log/agents/ConfigAgent-681 Fri Jul 22 12:29:29 2022 <===                                                                                                       │
│              │                     │             │ ===== Output from /usr/bin/ConfigAgent [] (PID=681) started Jul 22 12:28:50.103186 ===                                                                                                                       │
│              │                     │             │ EntityManager::doBackoff waiting for connection .....ok                                                                                                                                                      │
│              │                     │             │ 2022-07-22 12:29:44.118906  1170 Log                  0 %SYS-5-CONFIG_E: Enter configuration mode from console by root on vty22 (UnknownIpAddr)                                                              │
│              │                     │             │ 2022-07-22 12:29:48.637460  1170 Log                  0 %SYS-5-CONFIG_STARTUP: Startup config saved from system:/running-config by root on vty22 (UnknownIpAddr).                                            │
│              │                     │             │ 2022-07-22 12:29:48.861016  1170 Log                  0 %SYS-5-CONFIG_I: Configured from console by root on vty22 (UnknownIpAddr)                                                                            │
│              │                     │             │ CLI Exception: Internal error <class 'CliParserCommon.AuthzDeniedError'>: Authorization denied for command 'show logging last 7 days threshold warnings': Cannot authorize command for unknown sessionId 121 │
│              │                     │             │ CLI Exception: Traceback (most recent call last):                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 515, in _execute                                                                                                                    │
│              │                     │             │ CLI Exception:     result = self._runCmd( command, expandAliases )                                                                                                                                           │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 489, in _runCmd                                                                                                                     │
│              │                     │             │ CLI Exception:     return self.session_.runTokenizedCmd( expandedTokens, aaa=aaa, fromCapi=True )                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1142, in runTokenizedCmd                                                                                                   │
│              │                     │             │ CLI Exception:     authz=aaa, acct=aaa )                                                                                                                                                                     │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 196, in wrapper                                                                                                            │
│              │                     │             │ CLI Exception:     return func( *args, **kwargs )                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 923, in _invokeValueFunc                                                                                                   │
│              │                     │             │ CLI Exception:     self.performAaa( authz, acct, mode, parseResults )                                                                                                                                        │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1044, in performAaa                                                                                                        │
│              │                     │             │ CLI Exception:     raise CliParser.AuthzDeniedError( cmd, message )                                                                                                                                          │
│              │                     │             │ CLI Exception: AuthzDeniedError: Authorization denied for command 'show logging last 7 days threshold warnings': Cannot authorize command for unknown sessionId 121                                          │
│              │                     │             │ CLI Exception:                                                                                                                                                                                               │
│              │                     │             │ ERROR: [Errno 32] Broken pipe                                                                                                                                                                                │
│              │                     │             │ Traceback (most recent call last):                                                                                                                                                                           │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 108, in processRequest                                                                                                                        │
│              │                     │             │     self._processRequestInternal( request )                                                                                                                                                                  │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 138, in _processRequestInternal                                                                                                               │
│              │                     │             │     self._processRequestNonStreaming( procedure, params )                                                                                                                                                    │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 174, in _processRequestNonStreaming                                                                                                           │
│              │                     │             │     os.write( self.outputFd_, i )                                                                                                                                                                            │
│              │                     │             │ OSError: [Errno 32] Broken pipe                                                                                                                                                                              │
│              │                     │             │ CLI Exception: Internal error <class 'CliParserCommon.AuthzDeniedError'>: Authorization denied for command 'show processes top once': Cannot authorize command for unknown sessionId 131                     │
│              │                     │             │ CLI Exception: Traceback (most recent call last):                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 515, in _execute                                                                                                                    │
│              │                     │             │ CLI Exception:     result = self._runCmd( command, expandAliases )                                                                                                                                           │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 489, in _runCmd                                                                                                                     │
│              │                     │             │ CLI Exception:     return self.session_.runTokenizedCmd( expandedTokens, aaa=aaa, fromCapi=True )                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1142, in runTokenizedCmd                                                                                                   │
│              │                     │             │ CLI Exception:     authz=aaa, acct=aaa )                                                                                                                                                                     │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 196, in wrapper                                                                                                            │
│              │                     │             │ CLI Exception:     return func( *args, **kwargs )                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 923, in _invokeValueFunc                                                                                                   │
│              │                     │             │ CLI Exception:     self.performAaa( authz, acct, mode, parseResults )                                                                                                                                        │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1044, in performAaa                                                                                                        │
│              │                     │             │ CLI Exception:     raise CliParser.AuthzDeniedError( cmd, message )                                                                                                                                          │
│              │                     │             │ CLI Exception: AuthzDeniedError: Authorization denied for command 'show processes top once': Cannot authorize command for unknown sessionId 131                                                              │
│              │                     │             │ CLI Exception:                                                                                                                                                                                               │
│              │                     │             │ ERROR: [Errno 32] Broken pipe                                                                                                                                                                                │
│              │                     │             │ Traceback (most recent call last):                                                                                                                                                                           │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 108, in processRequest                                                                                                                        │
│              │                     │             │     self._processRequestInternal( request )                                                                                                                                                                  │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 138, in _processRequestInternal                                                                                                               │
│              │                     │             │     self._processRequestNonStreaming( procedure, params )                                                                                                                                                    │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 174, in _processRequestNonStreaming                                                                                                           │
│              │                     │             │     os.write( self.outputFd_, i )                                                                                                                                                                            │
│              │                     │             │ OSError: [Errno 32] Broken pipe                                                                                                                                                                              │
│              │                     │             │ CLI Exception: Internal error <class 'CliParserCommon.AuthzDeniedError'>: Authorization denied for command 'show ntp status': Cannot authorize command for unknown sessionId 141                             │
│              │                     │             │ CLI Exception: Traceback (most recent call last):                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 515, in _execute                                                                                                                    │
│              │                     │             │ CLI Exception:     result = self._runCmd( command, expandAliases )                                                                                                                                           │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 489, in _runCmd                                                                                                                     │
│              │                     │             │ CLI Exception:     return self.session_.runTokenizedCmd( expandedTokens, aaa=aaa, fromCapi=True )                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1142, in runTokenizedCmd                                                                                                   │
│              │                     │             │ CLI Exception:     authz=aaa, acct=aaa )                                                                                                                                                                     │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 196, in wrapper                                                                                                            │
│              │                     │             │ CLI Exception:     return func( *args, **kwargs )                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 923, in _invokeValueFunc                                                                                                   │
│              │                     │             │ CLI Exception:     self.performAaa( authz, acct, mode, parseResults )                                                                                                                                        │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1044, in performAaa                                                                                                        │
│              │                     │             │ CLI Exception:     raise CliParser.AuthzDeniedError( cmd, message )                                                                                                                                          │
│              │                     │             │ CLI Exception: AuthzDeniedError: Authorization denied for command 'show ntp status': Cannot authorize command for unknown sessionId 141                                                                      │
│              │                     │             │ CLI Exception:                                                                                                                                                                                               │
│              │                     │             │ ERROR: [Errno 32] Broken pipe                                                                                                                                                                                │
│              │                     │             │ Traceback (most recent call last):                                                                                                                                                                           │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 108, in processRequest                                                                                                                        │
│              │                     │             │     self._processRequestInternal( request )                                                                                                                                                                  │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 138, in _processRequestInternal                                                                                                               │
│              │                     │             │     self._processRequestNonStreaming( procedure, params )                                                                                                                                                    │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 174, in _processRequestNonStreaming                                                                                                           │
│              │                     │             │     os.write( self.outputFd_, i )                                                                                                                                                                            │
│              │                     │             │ OSError: [Errno 32] Broken pipe                                                                                                                                                                              │
│              │                     │             │ CLI Exception: Internal error <class 'CliParserCommon.AuthzDeniedError'>: Authorization denied for command 'show ip route summary': Cannot authorize command for unknown sessionId 156                       │
│              │                     │             │ CLI Exception: Traceback (most recent call last):                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 515, in _execute                                                                                                                    │
│              │                     │             │ CLI Exception:     result = self._runCmd( command, expandAliases )                                                                                                                                           │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 489, in _runCmd                                                                                                                     │
│              │                     │             │ CLI Exception:     return self.session_.runTokenizedCmd( expandedTokens, aaa=aaa, fromCapi=True )                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1142, in runTokenizedCmd                                                                                                   │
│              │                     │             │ CLI Exception:     authz=aaa, acct=aaa )                                                                                                                                                                     │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 196, in wrapper                                                                                                            │
│              │                     │             │ CLI Exception:     return func( *args, **kwargs )                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 923, in _invokeValueFunc                                                                                                   │
│              │                     │             │ CLI Exception:     self.performAaa( authz, acct, mode, parseResults )                                                                                                                                        │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1044, in performAaa                                                                                                        │
│              │                     │             │ CLI Exception:     raise CliParser.AuthzDeniedError( cmd, message )                                                                                                                                          │
│              │                     │             │ CLI Exception: AuthzDeniedError: Authorization denied for command 'show ip route summary': Cannot authorize command for unknown sessionId 156                                                                │
│              │                     │             │ CLI Exception:                                                                                                                                                                                               │
│              │                     │             │ ERROR: [Errno 32] Broken pipe                                                                                                                                                                                │
│              │                     │             │ Traceback (most recent call last):                                                                                                                                                                           │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 108, in processRequest                                                                                                                        │
│              │                     │             │     self._processRequestInternal( request )                                                                                                                                                                  │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 138, in _processRequestInternal                                                                                                               │
│              │                     │             │     self._processRequestNonStreaming( procedure, params )                                                                                                                                                    │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 174, in _processRequestNonStreaming                                                                                                           │
│              │                     │             │     os.write( self.outputFd_, i )                                                                                                                                                                            │
│              │                     │             │ OSError: [Errno 32] Broken pipe                                                                                                                                                                              │
│              │                     │             │                                                                                                                                                                                                              │
│              │                     │             │                                                                                                                                                                                                              │
│ 192.168.0.11 │ verify_eos_version  │ failure     │ device is running version 4.27.3F-26379303.4273F (engineering build) not in expected version                                                                                                                 │
│ 192.168.0.11 │ verify_uptime       │ success     │                                                                                                                                                                                                              │
│ 192.168.0.11 │ verify_reload_cause │ error       │ 'response'                                                                                                                                                                                                   │
│ 192.168.0.11 │ verify_coredump     │ success     │                                                                                                                                                                                                              │
│ 192.168.0.11 │ verify_agent_logs   │ success     │                                                                                                                                                                                                              │
│ 192.168.0.12 │ verify_eos_version  │ failure     │ device is running version 4.27.3F-26379303.4273F (engineering build) not in expected version                                                                                                                 │
│ 192.168.0.12 │ verify_uptime       │ success     │                                                                                                                                                                                                              │
│ 192.168.0.12 │ verify_reload_cause │ error       │ 'response'                                                                                                                                                                                                   │
│ 192.168.0.12 │ verify_coredump     │ success     │                                                                                                                                                                                                              │
│ 192.168.0.12 │ verify_agent_logs   │ failure     │ device reported some agent crashes: ===> /var/log/agents/ConfigAgent-682 Fri Jul 22 12:29:39 2022 <===                                                                                                       │
│              │                     │             │ ===== Output from /usr/bin/ConfigAgent [] (PID=682) started Jul 22 12:28:53.051363 ===                                                                                                                       │
│              │                     │             │ EntityManager::doBackoff waiting for connection .......ok                                                                                                                                                    │
│              │                     │             │ 2022-07-22 12:29:48.920598  1161 Log                  0 %SYS-5-CONFIG_E: Enter configuration mode from console by root on vty20 (UnknownIpAddr)                                                              │
│              │                     │             │ 2022-07-22 12:29:52.078253  1161 Log                  0 %SYS-5-CONFIG_STARTUP: Startup config saved from system:/running-config by root on vty20 (UnknownIpAddr).                                            │
│              │                     │             │ 2022-07-22 12:29:52.302700  1161 Log                  0 %SYS-5-CONFIG_I: Configured from console by root on vty20 (UnknownIpAddr)                                                                            │
│              │                     │             │ CLI Exception: Internal error <class 'CliParserCommon.AuthzDeniedError'>: Authorization denied for command 'show version': Cannot authorize command for unknown sessionId 4                                  │
│              │                     │             │ CLI Exception: Traceback (most recent call last):                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 515, in _execute                                                                                                                    │
│              │                     │             │ CLI Exception:     result = self._runCmd( command, expandAliases )                                                                                                                                           │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/CliApi.py", line 489, in _runCmd                                                                                                                     │
│              │                     │             │ CLI Exception:     return self.session_.runTokenizedCmd( expandedTokens, aaa=aaa, fromCapi=True )                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1142, in runTokenizedCmd                                                                                                   │
│              │                     │             │ CLI Exception:     authz=aaa, acct=aaa )                                                                                                                                                                     │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 196, in wrapper                                                                                                            │
│              │                     │             │ CLI Exception:     return func( *args, **kwargs )                                                                                                                                                            │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 923, in _invokeValueFunc                                                                                                   │
│              │                     │             │ CLI Exception:     self.performAaa( authz, acct, mode, parseResults )                                                                                                                                        │
│              │                     │             │ CLI Exception:   File "/usr/lib/python2.7/site-packages/BasicCliSession.py", line 1044, in performAaa                                                                                                        │
│              │                     │             │ CLI Exception:     raise CliParser.AuthzDeniedError( cmd, message )                                                                                                                                          │
│              │                     │             │ CLI Exception: AuthzDeniedError: Authorization denied for command 'show version': Cannot authorize command for unknown sessionId 4                                                                           │
│              │                     │             │ CLI Exception:                                                                                                                                                                                               │
│              │                     │             │ ERROR: [Errno 32] Broken pipe                                                                                                                                                                                │
│              │                     │             │ Traceback (most recent call last):                                                                                                                                                                           │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 108, in processRequest                                                                                                                        │
│              │                     │             │     self._processRequestInternal( request )                                                                                                                                                                  │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 138, in _processRequestInternal                                                                                                               │
│              │                     │             │     self._processRequestNonStreaming( procedure, params )                                                                                                                                                    │
│              │                     │             │   File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 174, in _processRequestNonStreaming                                                                                                           │
│              │                     │             │     os.write( self.outputFd_, i )                                                                                                                                                                            │
│              │                     │             │ OSError: [Errno 32] Broken pipe                                                                                                                                                                              │
│              │                     │             │                                                                                                                                                                                                              │
│              │                     │             │                                                                                                                                                                                                              │
│ 192.168.0.13 │ verify_eos_version  │ failure     │ device is running version 4.27.3F-26379303.4273F (engineering build) not in expected version                                                                                                                 │
│ 192.168.0.13 │ verify_uptime       │ success     │                                                                                                                                                                                                              │
│ 192.168.0.13 │ verify_reload_cause │ error       │ 'response'                                                                                                                                                                                                   │
│ 192.168.0.13 │ verify_coredump     │ success     │                                                                                                                                                                                                              │
│ 192.168.0.13 │ verify_agent_logs   │ success     │                                                                                                                                                                                                              │
│ 192.168.0.14 │ verify_eos_version  │ failure     │ device is running version 4.27.3F-26379303.4273F (engineering build) not in expected version                                                                                                                 │
│ 192.168.0.14 │ verify_uptime       │ success     │                                                                                                                                                                                                              │
│ 192.168.0.14 │ verify_reload_cause │ error       │ 'response'                                                                                                                                                                                                   │
│ 192.168.0.14 │ verify_coredump     │ success     │                                                                                                                                                                                                              │
│ 192.168.0.14 │ verify_agent_logs   │ success     │                                                                                                                                                                                                              │
│ 192.168.0.15 │ verify_eos_version  │ failure     │ device is running version 4.27.3F-26379303.4273F (engineering build) not in expected version                                                                                                                 │
│ 192.168.0.15 │ verify_uptime       │ success     │                                                                                                                                                                                                              │
│ 192.168.0.15 │ verify_reload_cause │ error       │ 'response'                                                                                                                                                                                                   │
│ 192.168.0.15 │ verify_coredump     │ success     │                                                                                                                                                                                                              │
│ 192.168.0.15 │ verify_agent_logs   │ success     │                                                                                                                                                                                                              │
└──────────────┴─────────────────────┴─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
